from numpy import load
import matplotlib.pyplot as plt
# reward_sarsa0=load('reward_sarsa0.npy')
# reward_monte=load('montecarlo_reward.npy')
# reward_sarsal=load('sarsalamda_reward.npy')
# reward_sarsab=load('total_reward_backview_sarsa.npy')
rward_sasra25=load('total_reward_backview_sarsa6x6.npy')
# reward_sarsa50=load('total_reward_backview_sarsa50.npy')
# reward_q=load("q_learning_reward.npy")
# reward_q_100=load("q_learning_reward100.npy")

# fig1=plt.figure(figsize=(8,4))
# plt.plot(reward_monte,label="monte-carlo")
# # plt.plot(reward_sarsa0,label="SARSA")
# plt.plot(reward_sarsal,label="SARSAλ")
# plt.plot(reward_sarsab,label="backward_view_SARSA")
# plt.plot(reward_q_100,label="Q_learning")
# plt.xlabel("Episode")
# plt.ylabel("Reward")
# plt.grid()
# plt.legend()
# fig2=plt.figure(figsize=(8,4))
# plt.plot(reward_sarsab,label="150-episodes")
plt.plot(rward_sasra25,label="SARSABackwardView")
# plt.plot(reward_sarsa50,label="50-episodes")
plt.legend()
plt.xlabel("Episodes")
plt.ylabel("Reward")
plt.grid()
plt.show()